config/routes.rb
Rails.application.routes.draw do
  root to: 'material_sources#index'
  resources :material_sources
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # Returns array of hashes with history of changed fields
  #   if audits plugin is added in to model
  def changes
    return unless respond_to?(:audits)
    audits.each_with_object([]) do |audit, versions|
      versions << audit.audited_changes.merge!("changed_at" => audit.created_at)
    end
  end
end

app/models/concerns/content_fetching_helper.rb
# frozen-string-literal: true

#
module ContentFetchingHelper
  # Setting attributes from XML to attributes of calling record.
  def set_content
    if xml_content.blank?
      errors.add(:url, I18n.t('material_source.errors.url.unparseble'))
      return false
    end

    assign_attributes(
      supplier_name: xml_content['supplierName'] || xml_content['supplierInfo'],
      title: xml_content['title'],
      episode: xml_content['episode'],
      year: xml_content['year'],
      duration: parsed_duration,
      aspect_ratio: xml_content['aspectRatio']
    )
  end

  private

  # Splits duration string to days, hours, minutes and seconds.
  #   Then calculates them and returns duration in seconds.
  def parsed_duration
    days, hours, minutes, seconds = xml_content['duration'].split(':').map(&:to_i)
    days * 1.day.seconds + hours * 1.hour.seconds + minutes * 1.minute.seconds + seconds
  end

  def xml_content
    xml_service.content
  end

  def xml_service
    @_xml_service ||= MaterialSourceXMLFetchingService.new(url)
  end
end

app/models/material_source.rb
# == Schema Information
#
# Table name: material_sources
#
#  id            :integer          not null, primary key
#  url           :string           not null
#  supplier_name :string
#  title         :string
#  episode       :string
#  year          :string
#  duration      :string
#  aspect_ratio  :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class MaterialSource < ApplicationRecord
  include ContentFetchingHelper

  validates :url, presence: true, uniqueness: true, url: { no_local: true }
  validates_presence_of :supplier_name, :title, :episode, :year, :duration, :aspect_ratio, on: :create

  audited only: [:supplier_name, :title, :episode, :year, :duration, :aspect_ratio]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/material_sources_controller.rb
class MaterialSourcesController < ApplicationController
  def index
    @sources = MaterialSource.all
    respond_to do |format|
      format.html
      format.json { render json: @sources }
    end
  end

  def new
    @source = MaterialSource.new
  end

  def create
    @source = MaterialSource.new(source_params)
    return render(:new) if @source.invalid?(:url)
    @source.set_content
    return render(:new) if @source.errors.present?
    @source.save && redirect_to(root_path)
  end

  def show
    find_material_source
    render json: @source
  end

  def edit
    find_material_source
  end

  def update
    find_material_source
    @source.update_attributes(source_params) ? redirect_to(@source) : render(:edit)
  end

  def destroy
    find_material_source
    @source.destroy && redirect_to(root_path)
  end

  private

  def find_material_source
    @source = MaterialSource.find(params[:id])
  end

  def source_params
    params.require(:material_source).permit(:url, :title, :episode, :year, :duration, :aspect_ratio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    ul.nav.navbar-nav
      li = link_to 'Materials', root_path
      li = link_to 'Materials in JSON', material_sources_path(format: :json)
      li = link_to 'Add New Material', new_material_source_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Honeycomb
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  body
    = render partial: 'layouts/navbar'
    .container-fluid
      .row
        = yield

app/views/material_sources/_material_source.html.slim
tr
  td = source.id
  td
    => source.duration
    | sec
  td
    p
      b Title:
      =< source.title
    p
      b Year:
      =< source.year
    p
      b Episode:
      =< source.episode
    p
      b Supplier Info:
      =< source.supplier_name
  td = source.created_at.to_formatted_s(:long)
  td
    span.label.label-success = link_to 'JSON', material_source_path(source, format: :json)
    span.label.label-info = link_to 'Edit', edit_material_source_path(source)
    span.label.label-danger = link_to 'Delete', source, method: :delete

app/views/material_sources/edit.html.slim
.col-md-6.col-md-offset-3
  = simple_form_for @source, html: { class: 'form-group' } do |f|
    = f.input :title, class: 'form-control', label: 'Title'
    = f.input :episode, class: 'form-control', label: 'Episode'
    = f.input :year, class: 'form-control', label: 'Year'
    = f.input :duration, class: 'form-control', label: 'Duration in Seconds'
    = f.input :aspect_ratio, class: 'form-control', label: 'Aspect Ratio'

    .btn-group
      = link_to 'Cancel', :back, class: 'btn btn-default'
      = f.submit class: 'btn btn-default'

app/views/material_sources/index.html.slim
.col-md-6.col-md-offset-3
  table.table
    thead
      tr
        th Material ID
        th Duration
        th Info
        th Created
        th
    = render partial: 'material_source', collection: @sources, as: :source

app/views/material_sources/new.html.slim
.col-md-6.col-md-offset-3
  = simple_form_for @source, html: { class: 'form-group' } do |f|
    = f.input :url, class: 'form-control', label: 'Material source URL'
    = f.submit class: 'btn btn-default'